name: lectura
description: "A Flutter app to keep track of your readings."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.8.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true