name: lectura
description: "A Flutter app to keep track of your readings."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true